# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_score', models.IntegerField(default=0)),
                ('answer_counting', models.CharField(default='0', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(default='', max_length=128)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('question', models.CharField(default='', max_length=255)),
                ('right_answer', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, unique=True)),
                ('session', models.CharField(max_length=255, unique=True)),
                ('weapp_session', models.CharField(max_length=255, unique=True)),
                ('nick_name', models.CharField(default='', max_length=128)),
                ('avatar', models.CharField(default='', max_length=128)),
                ('answer_count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.AnswerCount')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.QuestionSet'),
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together=set([('question', 'order')]),
        ),
    ]
