# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180411_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answer_count',
        ),
        migrations.AddField(
            model_name='user',
            name='answer_counting',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='answer_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AnswerCount',
        ),
    ]
