# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180411_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='content',
        ),
        migrations.AddField(
            model_name='chapter',
            name='Knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='api.Knowledge'),
        ),
    ]
