# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180414_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choose', models.CharField(default='', max_length=16)),
                ('choose_status', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='api.QuestionSet')),
            ],
        ),
    ]
