# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='question',
        ),
        migrations.AddField(
            model_name='questionset',
            name='choose_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='user_choose',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
