# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180415_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choose', models.CharField(default='', max_length=16)),
                ('choose_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='choose_status',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='user_choose',
        ),
        migrations.AddField(
            model_name='attribute',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='api.QuestionSet'),
        ),
    ]
